name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  node-ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18, 20]
    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configure Node cache
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: os-agent/package-lock.json

      - name: Install deps (os-agent)
        working-directory: ./os-agent
        run: npm ci

      - name: Run lint
        working-directory: ./os-agent
        run: npm run lint

      - name: Run tests
        working-directory: ./os-agent
        run: npm test
